// Login Page
export const APP_INIT = 'APP_INIT'

// User Page
export const HTTP_USER_FETCHING = 'HTTP_USER_FETCHING'
export const HTTP_USER_SUCCESS = 'HTTP_USER_SUCCESS'
export const HTTP_USER_FAILED = 'HTTP_USER_FAILED'

// User Selected Page
export const HTTP_USER_SELECTED_FETCHING = 'HTTP_USER_SELECTED_FETCHING'
export const HTTP_USER_SELECTED_SUCCESS = 'HTTP_USER_SELECTED_SUCCESS'
export const HTTP_USER_SELECTED_FAILED = 'HTTP_USER_SELECTED_FAILED'

// Role Page
export const HTTP_ROLE_FETCHING = 'HTTP_ROLE_FETCHING'
export const HTTP_ROLE_SUCCESS = 'HTTP_ROLE_SUCCESS'
export const HTTP_ROLE_FAILED = 'HTTP_ROLE_FAILED'

// Leave Record Page
export const HTTP_LEAVERECORD_FETCHING = 'HTTP_LEAVERECORD_FETCHING'
export const HTTP_LEAVERECORD_SUCCESS = 'HTTP_LEAVERECORD_SUCCESS'
export const HTTP_LEAVERECORD_FAILED = 'HTTP_LEAVERECORD_FAILED'

// User Edit Page
export const HTTP_USEREDIT_FETCHING = 'HTTP_USEREDIT_FETCHING'
export const HTTP_USEREDIT_SUCCESS = 'HTTP_USEREDIT_SUCCESS'
export const HTTP_USEREDIT_FAILED = 'HTTP_USEREDIT_FAILED'

// Login Page
export const HTTP_LOGIN_FETCHING = 'HTTP_LOGIN_FETCHING'
export const HTTP_LOGIN_SUCCESS = 'HTTP_LOGIN_SUCCESS'
export const HTTP_LOGIN_FAILED = 'HTTP_LOGIN_FAILED'
export const HTTP_LOGOUT = 'HTTP_LOGOUT'

// Farmer register Page
export const HTTP_REGISTER_FETCHING = 'HTTP_REGISTER_FETCHING'
export const HTTP_REGISTER_SUCCESS = 'HTTP_REGISTER_SUCCESS'
export const HTTP_REGISTER_FAILED = 'HTTP_REGISTER_FAILED'
export const HTTP_REGISTER_SELECTED_FETCHING = 'HTTP_REGISTER_SELECTED_FETCHING'  
export const HTTP_REGISTER_SELECTED_SUCCESS = 'HTTP_REGISTER_SELECTED_SUCCESS'  
export const HTTP_REGISTER_SELECTED_FAILED = 'HTTP_REGISTER_SELECTED_FAILED'  

// Dashboard Page
export const HTTP_DASHBOARD_FETCHING = 'HTTP_DASHBOARD_FETCHING'
export const HTTP_DASHBOARD_SUCCESS = 'HTTP_DASHBOARD_SUCCESS'
export const HTTP_DASHBOARD_FAILED = 'HTTP_DASHBOARD_FAILED'

// Log Page
export const HTTP_LOG_FETCHING = 'HTTP_LOG_FETCHING'
export const HTTP_LOG_SUCCESS = 'HTTP_LOG_SUCCESS'
export const HTTP_LOG_FAILED = 'HTTP_LOG_FAILED'
export const HTTP_LOG_SELECTED_FETCHING = 'HTTP_LOG_SELECTED_FETCHING'  
export const HTTP_LOG_SELECTED_SUCCESS = 'HTTP_LOG_SELECTED_SUCCESS'  
export const HTTP_LOG_SELECTED_FAILED = 'HTTP_LOG_SELECTED_FAILED'  

// Student Page
export const HTTP_STUDENT_FETCHING = 'HTTP_STUDENT_FETCHING'
export const HTTP_STUDENT_SUCCESS = 'HTTP_STUDENT_SUCCESS'
export const HTTP_STUDENT_FAILED = 'HTTP_STUDENT_FAILED'

// Student Grant Page ทุนการศึกษา
export const HTTP_STUDENTGRANT_FETCHING = 'HTTP_STUDENTGRANT_FETCHING'
export const HTTP_STUDENTGRANT_SUCCESS = 'HTTP_STUDENTGRANT_SUCCESS'
export const HTTP_STUDENTGRANT_FAILED = 'HTTP_STUDENTGRANT_FAILED'

// Staff Page
export const HTTP_STAFF_FETCHING = 'HTTP_STAFF_FETCHING'
export const HTTP_STAFF_SUCCESS = 'HTTP_STAFF_SUCCESS'
export const HTTP_STAFF_FAILED = 'HTTP_STAFF_FAILED'

// Staff upload file Page
export const HTTP_STAFFUPLOADFILE_FETCHING = 'HTTP_STAFFUPLOADFILE_FETCHING'
export const HTTP_STAFFUPLOADFILE_SUCCESS = 'HTTP_STAFFUPLOADFILE_SUCCESS'
export const HTTP_STAFFUPLOADFILE_FAILED = 'HTTP_STAFFUPLOADFILE_FAILED'

// Staff type Page
export const HTTP_STAFFTYPE_FETCHING = 'HTTP_STAFFTYPE_FETCHING'
export const HTTP_STAFFTYPE_SUCCESS = 'HTTP_STAFFTYPE_SUCCESS'
export const HTTP_STAFFTYPE_FAILED = 'HTTP_STAFFTYPE_FAILED'

// Staff Education Page
export const HTTP_STAFFEDUCATION_FETCHING = 'HTTP_STAFFEDUCATION_FETCHING'
export const HTTP_STAFFEDUCATION_SUCCESS = 'HTTP_STAFFEDUCATION_SUCCESS'
export const HTTP_STAFFEDUCATION_FAILED = 'HTTP_STAFFEDUCATION_FAILED'

// Publication Page
export const HTTP_PUBLICATION_FETCHING = 'HTTP_PUBLICATION_FETCHING'
export const HTTP_PUBLICATION_SUCCESS = 'HTTP_PUBLICATION_SUCCESS'
export const HTTP_PUBLICATION_FAILED = 'HTTP_PUBLICATION_FAILED'

// Project Page
export const HTTP_PROJECT_FETCHING = 'HTTP_PROJECT_FETCHING'
export const HTTP_PROJECT_SUCCESS = 'HTTP_PROJECT_SUCCESS'
export const HTTP_PROJECT_FAILED = 'HTTP_PROJECT_FAILED'

// Document Page
export const HTTP_DOCUMENT_FETCHING = 'HTTP_DOCUMENT_FETCHING'
export const HTTP_DOCUMENT_SUCCESS = 'HTTP_DOCUMENT_SUCCESS'
export const HTTP_DOCUMENT_FAILED = 'HTTP_DOCUMENT_FAILED'

// Document Page
export const HTTP_DEPARTMENT_FETCHING = 'HTTP_DEPARTMENT_FETCHING'
export const HTTP_DEPARTMENT_SUCCESS = 'HTTP_DEPARTMENT_SUCCESS'
export const HTTP_DEPARTMENT_FAILED = 'HTTP_DEPARTMENT_FAILED'

// Academic Program (ฝ่ายวิชาการ) Page
export const HTTP_ACADEMIC_FETCHING = 'HTTP_ACADEMIC_FETCHING'
export const HTTP_ACADEMIC_SUCCESS = 'HTTP_ACADEMIC_SUCCESS'
export const HTTP_ACADEMIC_FAILED = 'HTTP_ACADEMIC_FAILED'
export const HTTP_ACADEMIC_SELECTED_FETCHING = 'HTTP_ACADEMIC_SELECTED_FETCHING'  
export const HTTP_ACADEMIC_SELECTED_SUCCESS = 'HTTP_ACADEMIC_SELECTED_SUCCESS'  
export const HTTP_ACADEMIC_SELECTED_FAILED = 'HTTP_ACADEMIC_SELECTED_FAILED'  

// Admission Plan Page
export const HTTP_ADMISSIONPLAN_FETCHING = 'HTTP_ADMISSIONPLAN_FETCHING'
export const HTTP_ADMISSIONPLAN_SUCCESS = 'HTTP_ADMISSIONPLAN_SUCCESS'
export const HTTP_ADMISSIONPLAN_FAILED = 'HTTP_ADMISSIONPLAN_FAILED'
export const HTTP_ADMISSIONPLAN_SELECTED_FETCHING = 'HTTP_ADMISSIONPLAN_SELECTED_FETCHING'  
export const HTTP_ADMISSIONPLAN_SELECTED_SUCCESS = 'HTTP_ADMISSIONPLAN_SELECTED_SUCCESS'  
export const HTTP_ADMISSIONPLAN_SELECTED_FAILED = 'HTTP_ADMISSIONPLAN_SELECTED_FAILED'  

// CONSTANTS
export const INIT = 'INIT';
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const SET_MAP_CONFIG = 'SET_MAP_CONFIG';
export const QUERY_SUCCESS = 'QUERY_SUCCESS';

// Error Code
export const E_PICKER_CANCELLED = 'E_PICKER_CANCELLED'
export const E_PICKER_CANNOT_RUN_CAMERA_ON_SIMULATOR =
  'E_PICKER_CANNOT_RUN_CAMERA_ON_SIMULATOR'
export const E_PERMISSION_MISSING = 'E_PERMISSION_MISSING'
export const E_PICKER_NO_CAMERA_PERMISSION = 'E_PICKER_NO_CAMERA_PERMISSION'
export const E_USER_CANCELLED = 'E_USER_CANCELLED'
export const E_UNKNOWN = 'E_UNKNOWN'
export const E_DEVELOPER_ERROR = 'E_DEVELOPER_ERROR'
export const TIMEOUT_NETWORK = 'ECONNABORTED' // request service timeout
export const NOT_CONNECT_NETWORK = 'NOT_CONNECT_NETWORK'

//////////////// Localization Begin ////////////////
export const NETWORK_CONNECTION_MESSAGE =
  'Cannot connect to server, Please try again.'
export const NETWORK_TIMEOUT_MESSAGE =
  'A network timeout has occurred, Please try again.'
export const UPLOAD_PHOTO_FAIL_MESSAGE =
  'An error has occurred. The photo was unable to upload.'

// export const apiUrl = 'https://coral-app-hwkgh.ondigitalocean.app/api/v2'
const serviceUrl = process.env.REACT_APP_SERVICE_URL
export const apiUrl = `${serviceUrl}/api/v2`

// export const imageUrl = 'http://61.19.101.249:3000'
export const imageUrl = `${serviceUrl}:3000`

export const YES = 'YES'
export const NO = 'NO'
export const OK = 'ok'
export const NOK = 'nok'
export const LOGIN_STATUS = 'LOGIN_STATUS'
export const USER_ROLES = 'USER_ROLES'
export const TOKEN = 'HerbHukToken'

export const server = {
  LETIN_URL: `user/letin`,
  LOGIN_URL: `user/login`,
  // LOGIN_URL:`/auth`,
  // REGISTER_URL: `user/register`,
  USER_URL: `user`,
  ROLE_URL: `role`,
  VERIFY_URL: `user/verify`,
  AUTH_URL: `authen`,
  SYSTEM_URL: `system`,
  LOGIN_PASSED: `yes`,
  ACADEMIC_URL: `academicprogram`,
  ADMISSIONPLAN_URL: `admissionplan`,
  STUDENT_URL: `student`,
  STUDENTGRANT_URL: `studentgrant`,
  STAFF_URL: `staff`,
  STAFFUPLOADFILE_URL: `staff/uploadfile`,
  STAFFTYPE_URL: `stafftype`,
  LEAVERECORD_URL: `leaverecord`,
  STAFFEDUCATION_URL: `staffeducation`,
  PUBLICATION_URL: `publication`,
  PROJECT_URL: `project`,
  DOCUMENT_URL: `document`,
  DEPARTMENT_URL: `department`,
  LOG_URL: `log`,
  REGISTER_URL: `register`,
  DASHBOARD_URL: `dashboard`,
}

// To Make it more secure in JWT, so i'm used id (number) instead
export const ROLES =   {
  'User' : 2001,
  'Editor': 1976,
  'Admin': 5150
}

export const appRoutes = {
  USERS: '/users',
  USERS_LIST: '/users/list',
  USERS_ADD: '/users/add',
  UNKNOWN: '*'
}