// Login Page
export const APP_INIT = 'APP_INIT'

// User Page
export const HTTP_USER_FETCHING = 'HTTP_USER_FETCHING'
export const HTTP_USER_SUCCESS = 'HTTP_USER_SUCCESS'
export const HTTP_USER_FAILED = 'HTTP_USER_FAILED'

// User Selected Page
export const HTTP_USER_SELECTED_FETCHING = 'HTTP_USER_SELECTED_FETCHING'
export const HTTP_USER_SELECTED_SUCCESS = 'HTTP_USER_SELECTED_SUCCESS'
export const HTTP_USER_SELECTED_FAILED = 'HTTP_USER_SELECTED_FAILED'

// Role Page
export const HTTP_ROLE_FETCHING = 'HTTP_ROLE_FETCHING'
export const HTTP_ROLE_SUCCESS = 'HTTP_ROLE_SUCCESS'
export const HTTP_ROLE_FAILED = 'HTTP_ROLE_FAILED'

// User Edit Page
export const HTTP_USEREDIT_FETCHING = 'HTTP_USEREDIT_FETCHING'
export const HTTP_USEREDIT_SUCCESS = 'HTTP_USEREDIT_SUCCESS'
export const HTTP_USEREDIT_FAILED = 'HTTP_USEREDIT_FAILED'

// Login Page
export const HTTP_LOGIN_FETCHING = 'HTTP_LOGIN_FETCHING'
export const HTTP_LOGIN_SUCCESS = 'HTTP_LOGIN_SUCCESS'
export const HTTP_LOGIN_FAILED = 'HTTP_LOGIN_FAILED'
export const HTTP_LOGOUT = 'HTTP_LOGOUT'

// Register Page
// export const HTTP_REGISTER_FETCHING = 'HTTP_REGISTER_FETCHING'
// export const HTTP_REGISTER_SUCCESS = 'HTTP_REGISTER_SUCCESS'
// export const HTTP_REGISTER_FAILED = 'HTTP_REGISTER_FAILED'

// Entrepreneur type Page
export const HTTP_ENTRETYPE_FETCHING = 'HTTP_ENTRETYPE_FETCHING'
export const HTTP_ENTRETYPE_SUCCESS = 'HTTP_ENTRETYPE_SUCCESS'
export const HTTP_ENTRETYPE_FAILED = 'HTTP_ENTRETYPE_FAILED'

// Product type Page
export const HTTP_PRODUCTTYPE_FETCHING = 'HTTP_PRODUCTTYPE_FETCHING'
export const HTTP_PRODUCTTYPE_SUCCESS = 'HTTP_PRODUCTTYPE_SUCCESS'
export const HTTP_PRODUCTTYPE_FAILED = 'HTTP_PRODUCTTYPE_FAILED'

// Producing type Page
export const HTTP_PRODUCETYPE_FETCHING = 'HTTP_PRODUCETYPE_FETCHING'
export const HTTP_PRODUCETYPE_SUCCESS = 'HTTP_PRODUCETYPE_SUCCESS'
export const HTTP_PRODUCETYPE_FAILED = 'HTTP_PRODUCETYPE_FAILED'

// Standard type Page
export const HTTP_STANDARDTYPE_FETCHING = 'HTTP_STANDARDTYPE_FETCHING'
export const HTTP_STANDARDTYPE_SUCCESS = 'HTTP_STANDARDTYPE_SUCCESS'
export const HTTP_STANDARDTYPE_FAILED = 'HTTP_STANDARDTYPE_FAILED'

// Service type Page
export const HTTP_SERVICETYPE_FETCHING = 'HTTP_SERVICETYPE_FETCHING'
export const HTTP_SERVICETYPE_SUCCESS = 'HTTP_SERVICETYPE_SUCCESS'
export const HTTP_SERVICETYPE_FAILED = 'HTTP_SERVICETYPE_FAILED'

// Owner type Page
export const HTTP_OWNERTYPE_FETCHING = 'HTTP_OWNERTYPE_FETCHING'
export const HTTP_OWNERTYPE_SUCCESS = 'HTTP_OWNERTYPE_SUCCESS'
export const HTTP_OWNERTYPE_FAILED = 'HTTP_OWNERTYPE_FAILED'

// Dashboard Page
export const HTTP_DASHBOARD_FETCHING = 'HTTP_DASHBOARD_FETCHING'
export const HTTP_DASHBOARD_SUCCESS = 'HTTP_DASHBOARD_SUCCESS'
export const HTTP_DASHBOARD_FAILED = 'HTTP_DASHBOARD_FAILED'

// Land Page
export const HTTP_LAND_FETCHING = 'HTTP_LAND_FETCHING'
export const HTTP_LAND_SUCCESS = 'HTTP_LAND_SUCCESS'
export const HTTP_LAND_FAILED = 'HTTP_LAND_FAILED'

// Log Page
export const HTTP_LOG_FETCHING = 'HTTP_LOG_FETCHING'
export const HTTP_LOG_SUCCESS = 'HTTP_LOG_SUCCESS'
export const HTTP_LOG_FAILED = 'HTTP_LOG_FAILED'
export const HTTP_LOG_SELECTED_FETCHING = 'HTTP_LOG_SELECTED_FETCHING'  
export const HTTP_LOG_SELECTED_SUCCESS = 'HTTP_LOG_SELECTED_SUCCESS'  
export const HTTP_LOG_SELECTED_FAILED = 'HTTP_LOG_SELECTED_FAILED'  

// Marketplace Page
export const HTTP_MARKETPLACE_FETCHING = 'HTTP_MARKETPLACE_FETCHING'
export const HTTP_MARKETPLACE_SUCCESS = 'HTTP_MARKETPLACE_SUCCESS'
export const HTTP_MARKETPLACE_FAILED = 'HTTP_MARKETPLACE_FAILED'

// Herbal Marketplace Page
export const HTTP_HERBALMARKETPLACE_FETCHING = 'HTTP_HERBALMARKETPLACE_FETCHING'
export const HTTP_HERBALMARKETPLACE_SUCCESS = 'HTTP_HERBALMARKETPLACE_SUCCESS'
export const HTTP_HERBALMARKETPLACE_FAILED = 'HTTP_HERBALMARKETPLACE_FAILED'
export const HTTP_HERBALMARKETPLACE_SELECTED_FETCHING = 'HTTP_HERBALMARKETPLACE_SELECTED_FETCHING'  
export const HTTP_HERBALMARKETPLACE_SELECTED_SUCCESS = 'HTTP_HERBALMARKETPLACE_SELECTED_SUCCESS'  
export const HTTP_HERBALMARKETPLACE_SELECTED_FAILED = 'HTTP_HERBALMARKETPLACE_SELECTED_FAILED'  
// MAP only
export const HTTP_HERBALMARKETPLACE_MAP_FETCHING = 'HTTP_HERBALMARKETPLACE_MAP_FETCHING'
export const HTTP_HERBALMARKETPLACE_MAP_SUCCESS = 'HTTP_HERBALMARKETPLACE_MAP_SUCCESS'  
export const HTTP_HERBALMARKETPLACE_MAP_FAILED = 'HTTP_HERBALMARKETPLACE_MAP_FAILED'  

// Farmer Page
export const HTTP_FARMER_FETCHING = 'HTTP_FARMER_FETCHING'
export const HTTP_FARMER_SUCCESS = 'HTTP_FARMER_SUCCESS'
export const HTTP_FARMER_FAILED = 'HTTP_FARMER_FAILED'
export const HTTP_FARMER_SELECTED_FETCHING = 'HTTP_FARMER_SELECTED_FETCHING'  
export const HTTP_FARMER_SELECTED_SUCCESS = 'HTTP_FARMER_SELECTED_SUCCESS'  
export const HTTP_FARMER_SELECTED_FAILED = 'HTTP_FARMER_SELECTED_FAILED'  
export const HTTP_FARMER_CHANGE_PASSWORD_SUCCESS = 'HTTP_FARMER_CHANGE_PASSWORD_SUCCESS'  
export const HTTP_FARMER_CHANGE_PASSWORD_FAILURE = 'HTTP_FARMER_CHANGE_PASSWORD_FAILURE'  
export const HTTP_FARMER_SELFREGISTER_SUCCESS = 'HTTP_FARMER_SELFREGISTER_SUCCESS'  
export const HTTP_FARMER_SELFREGISTER_FAILURE = 'HTTP_FARMER_SELFREGISTER_FAILURE'  

// Outsource Page (แหล่งแปรรูป)
export const HTTP_OUTSOURCE_FETCHING = 'HTTP_OUTSOURCE_FETCHING'
export const HTTP_OUTSOURCE_SUCCESS = 'HTTP_OUTSOURCE_SUCCESS'
export const HTTP_OUTSOURCE_FAILED = 'HTTP_OUTSOURCE_FAILED'
export const HTTP_OUTSOURCE_SELECTED_FETCHING = 'HTTP_OUTSOURCE_SELECTED_FETCHING'  
export const HTTP_OUTSOURCE_SELECTED_SUCCESS = 'HTTP_OUTSOURCE_SELECTED_SUCCESS'  
export const HTTP_OUTSOURCE_SELECTED_FAILED = 'HTTP_OUTSOURCE_SELECTED_FAILED'  
// MAP only
export const HTTP_OUTSOURCE_MAP_FETCHING = 'HTTP_OUTSOURCE_MAP_FETCHING'
export const HTTP_OUTSOURCE_MAP_SUCCESS = 'HTTP_OUTSOURCE_MAP_SUCCESS'  
export const HTTP_OUTSOURCE_MAP_FAILED = 'HTTP_OUTSOURCE_MAP_FAILED'  

// Manufacturer Page (แหล่งแปรรูป)
export const HTTP_MANUFACTURER_FETCHING = 'HTTP_MANUFACTURER_FETCHING'
export const HTTP_MANUFACTURER_SUCCESS = 'HTTP_MANUFACTURER_SUCCESS'
export const HTTP_MANUFACTURER_FAILED = 'HTTP_MANUFACTURER_FAILED'
export const HTTP_MANUFACTURER_SELECTED_FETCHING = 'HTTP_MANUFACTURER_SELECTED_FETCHING'  
export const HTTP_MANUFACTURER_SELECTED_SUCCESS = 'HTTP_MANUFACTURER_SELECTED_SUCCESS'  
export const HTTP_MANUFACTURER_SELECTED_FAILED = 'HTTP_MANUFACTURER_SELECTED_FAILED'  
// MAP only
export const HTTP_MANUFACTURER_MAP_FETCHING = 'HTTP_MANUFACTURER_MAP_FETCHING'
export const HTTP_MANUFACTURER_MAP_SUCCESS = 'HTTP_MANUFACTURER_MAP_SUCCESS'  
export const HTTP_MANUFACTURER_MAP_FAILED = 'HTTP_MANUFACTURER_MAP_FAILED' 

// Researchinnovation Page (งานวิจัยและนวัตกรรม)
export const HTTP_RESEARCHINNOVATION_FETCHING = 'HTTP_RESEARCHINNOVATION_FETCHING'
export const HTTP_RESEARCHINNOVATION_SUCCESS = 'HTTP_RESEARCHINNOVATION_SUCCESS'
export const HTTP_RESEARCHINNOVATION_FAILED = 'HTTP_RESEARCHINNOVATION_FAILED'
export const HTTP_RESEARCHINNOVATION_SELECTED_FETCHING = 'HTTP_RESEARCHINNOVATION_SELECTED_FETCHING'  
export const HTTP_RESEARCHINNOVATION_SELECTED_SUCCESS = 'HTTP_RESEARCHINNOVATION_SELECTED_SUCCESS'  
export const HTTP_RESEARCHINNOVATION_SELECTED_FAILED = 'HTTP_RESEARCHINNOVATION_SELECTED_FAILED'  

// Philosopher Page (ปราชญ์)
export const HTTP_PHILOSOPHER_FETCHING = 'HTTP_PHILOSOPHER_FETCHING'
export const HTTP_PHILOSOPHER_SUCCESS = 'HTTP_PHILOSOPHER_SUCCESS'
export const HTTP_PHILOSOPHER_FAILED = 'HTTP_PHILOSOPHER_FAILED'
export const HTTP_PHILOSOPHER_SELECTED_FETCHING = 'HTTP_PHILOSOPHER_SELECTED_FETCHING'  
export const HTTP_PHILOSOPHER_SELECTED_SUCCESS = 'HTTP_PHILOSOPHER_SELECTED_SUCCESS'  
export const HTTP_PHILOSOPHER_SELECTED_FAILED = 'HTTP_PHILOSOPHER_SELECTED_FAILED'  


// Student Page
export const HTTP_STUDENT_FETCHING = 'HTTP_STUDENT_FETCHING'
export const HTTP_STUDENT_SUCCESS = 'HTTP_STUDENT_SUCCESS'
export const HTTP_STUDENT_FAILED = 'HTTP_STUDENT_FAILED'

// CollaborativeFarm Page (แปลงใหญ่)
export const HTTP_COLLABORATIVEFARM_FETCHING = 'HTTP_COLLABORATIVEFARM_FETCHING'
export const HTTP_COLLABORATIVEFARM_SUCCESS = 'HTTP_COLLABORATIVEFARM_SUCCESS'
export const HTTP_COLLABORATIVEFARM_FAILED = 'HTTP_COLLABORATIVEFARM_FAILED'
export const HTTP_COLLABORATIVEFARM_SELECTED_FETCHING = 'HTTP_COLLABORATIVEFARM_SELECTED_FETCHING'  
export const HTTP_COLLABORATIVEFARM_SELECTED_SUCCESS = 'HTTP_COLLABORATIVEFARM_SELECTED_SUCCESS'  
export const HTTP_COLLABORATIVEFARM_SELECTED_FAILED = 'HTTP_COLLABORATIVEFARM_SELECTED_FAILED'  

// Entrepreneurherbal Page (ผู้ประกอบการผลิตภัณฑ์สมุนไพร)
export const HTTP_ENTREPRENEURHERBAL_FETCHING = 'HTTP_ENTREPRENEURHERBAL_FETCHING'
export const HTTP_ENTREPRENEURHERBAL_SUCCESS = 'HTTP_ENTREPRENEURHERBAL_SUCCESS'
export const HTTP_ENTREPRENEURHERBAL_FAILED = 'HTTP_ENTREPRENEURHERBAL_FAILED'
export const HTTP_ENTREPRENEURHERBAL_SELECTED_FETCHING = 'HTTP_ENTREPRENEURHERBAL_SELECTED_FETCHING'  
export const HTTP_ENTREPRENEURHERBAL_SELECTED_SUCCESS = 'HTTP_ENTREPRENEURHERBAL_SELECTED_SUCCESS'  
export const HTTP_ENTREPRENEURHERBAL_SELECTED_FAILED = 'HTTP_ENTREPRENEURHERBAL_SELECTED_FAILED'  

// Entrepreneurmedical Page (ผู้ประกอบการด้านการแพทย์แผนไทย/สมุนไพร)
export const HTTP_ENTREPRENEURMEDICAL_FETCHING = 'HTTP_ENTREPRENEURMEDICAL_FETCHING'
export const HTTP_ENTREPRENEURMEDICAL_SUCCESS = 'HTTP_ENTREPRENEURMEDICAL_SUCCESS'
export const HTTP_ENTREPRENEURMEDICAL_FAILED = 'HTTP_ENTREPRENEURMEDICAL_FAILED'
export const HTTP_ENTREPRENEURMEDICAL_SELECTED_FETCHING = 'HTTP_ENTREPRENEURMEDICAL_SELECTED_FETCHING'  
export const HTTP_ENTREPRENEURMEDICAL_SELECTED_SUCCESS = 'HTTP_ENTREPRENEURMEDICAL_SELECTED_SUCCESS'  
export const HTTP_ENTREPRENEURMEDICAL_SELECTED_FAILED = 'HTTP_ENTREPRENEURMEDICAL_SELECTED_FAILED'  

export const HTTP_ENTREPRENEURMEDICAL_MAP_FETCHING = 'HTTP_ENTREPRENEURMEDICAL_MAP_FETCHING'  
export const HTTP_ENTREPRENEURMEDICAL_MAP_SUCCESS = 'HTTP_ENTREPRENEURMEDICAL_MAP_SUCCESS'  
export const HTTP_ENTREPRENEURMEDICAL_MAP_FAILED = 'HTTP_ENTREPRENEURMEDICAL_MAP_FAILED' 

// Farmer register Page
export const HTTP_REGISTER_FETCHING = 'HTTP_REGISTER_FETCHING'
export const HTTP_REGISTER_SUCCESS = 'HTTP_REGISTER_SUCCESS'
export const HTTP_REGISTER_FAILED = 'HTTP_REGISTER_FAILED'
export const HTTP_REGISTER_SELECTED_FETCHING = 'HTTP_REGISTER_SELECTED_FETCHING'  
export const HTTP_REGISTER_SELECTED_SUCCESS = 'HTTP_REGISTER_SELECTED_SUCCESS'  
export const HTTP_REGISTER_SELECTED_FAILED = 'HTTP_REGISTER_SELECTED_FAILED'  

// Farmgroup Page
export const HTTP_FARMERGROUP_FETCHING = 'HTTP_FARMERGROUP_FETCHING'
export const HTTP_FARMERGROUP_SUCCESS = 'HTTP_FARMERGROUP_SUCCESS'
export const HTTP_FARMERGROUP_FAILED = 'HTTP_FARMERGROUP_FAILED'
export const HTTP_FARMERGROUP_SELECTED_FETCHING = 'HTTP_FARMERGROUP_SELECTED_FETCHING'  
export const HTTP_FARMERGROUP_SELECTED_SUCCESS = 'HTTP_FARMERGROUP_SELECTED_SUCCESS'  
export const HTTP_FARMERGROUP_SELECTED_FAILED = 'HTTP_FARMERGROUP_SELECTED_FAILED'  

export const HTTP_FARMERGROUP_MAP_FETCHING = 'HTTP_FARMERGROUP_MAP_FETCHING'  
export const HTTP_FARMERGROUP_MAP_SUCCESS = 'HTTP_FARMERGROUP_MAP_SUCCESS'  
export const HTTP_FARMERGROUP_MAP_FAILED = 'HTTP_FARMERGROUP_MAP_FAILED'  

// Knowledgebase (องค์ความรู้การแพทย์แผนไทย) Page
export const HTTP_KNOWLEDGEBASE_FETCHING = 'HTTP_KNOWLEDGEBASE_FETCHING'
export const HTTP_KNOWLEDGEBASE_SUCCESS = 'HTTP_KNOWLEDGEBASE_SUCCESS'
export const HTTP_KNOWLEDGEBASE_FAILED = 'HTTP_KNOWLEDGEBASE_FAILED'
export const HTTP_KNOWLEDGEBASE_SELECTED_FETCHING = 'HTTP_KNOWLEDGEBASE_SELECTED_FETCHING'  
export const HTTP_KNOWLEDGEBASE_SELECTED_SUCCESS = 'HTTP_KNOWLEDGEBASE_SELECTED_SUCCESS'  
export const HTTP_KNOWLEDGEBASE_SELECTED_FAILED = 'HTTP_KNOWLEDGEBASE_SELECTED_FAILED'  

// Herbal Property (สรรพคุณ) Page
export const HTTP_PROPERTY_FETCHING = 'HTTP_PROPERTY_FETCHING'
export const HTTP_PROPERTY_SUCCESS = 'HTTP_PROPERTY_SUCCESS'
export const HTTP_PROPERTY_FAILED = 'HTTP_PROPERTY_FAILED'
export const HTTP_PROPERTY_SELECTED_FETCHING = 'HTTP_PROPERTY_SELECTED_FETCHING'  
export const HTTP_PROPERTY_SELECTED_SUCCESS = 'HTTP_PROPERTY_SELECTED_SUCCESS'  
export const HTTP_PROPERTY_SELECTED_FAILED = 'HTTP_PROPERTY_SELECTED_FAILED'  

// Herbal Page
export const HTTP_HERBAL_FETCHING = 'HTTP_HERBAL_FETCHING'
export const HTTP_HERBAL_SUCCESS = 'HTTP_HERBAL_SUCCESS'
export const HTTP_HERBAL_FAILED = 'HTTP_HERBAL_FAILED'
export const HTTP_HERBAL_SELECTED_FETCHING = 'HTTP_HERBAL_SELECTED_FETCHING'  
export const HTTP_HERBAL_SELECTED_SUCCESS = 'HTTP_HERBAL_SELECTED_SUCCESS'  
export const HTTP_HERBAL_SELECTED_FAILED = 'HTTP_HERBAL_SELECTED_FAILED'
export const HTTP_HERBAL_SELECTED_MAP_FETCHING = 'HTTP_HERBAL_SELECTED_MAP_FETCHING'  
export const HTTP_HERBAL_SELECTED_MAP_SUCCESS = 'HTTP_HERBAL_SELECTED_MAP_SUCCESS'  
export const HTTP_HERBAL_SELECTED_MAP_FAILED = 'HTTP_HERBAL_SELECTED_MAP_FAILED'
// Herbal Pagination
export const HTTP_HERBAL_PAGINATION_FETCHING = 'HTTP_HERBAL_PAGINATION_FETCHING'  
export const HTTP_HERBAL_PAGINATION_SUCCESS = 'HTTP_HERBAL_PAGINATION_SUCCESS'  
export const HTTP_HERBAL_PAGINATION_FAILED = 'HTTP_HERBAL_PAGINATION_FAILED' 
// Herbal Autosearch
export const HERBAL_SEARCH_FETCHING = 'HERBAL_SEARCH_FETCHING' 
export const HERBAL_SEARCH_SUCCESS = 'HERBAL_SEARCH_SUCCESS' 
export const HERBAL_SEARCH_FAILED = 'HERBAL_SEARCH_FAILED' 


// Herbal selection
export const SET_PLANTING_SELECTION = 'SET_PLANTING_SELECTION';  
export const SET_AMPHOE_SELECTION = 'SET_AMPHOE_SELECTION';  
export const SET_SOIL_FIELD_SELECTION = 'SET_SOIL_FIELD_SELECTION';  

// Herbal recommendation
export const HTTP_HERBAL_RECOMMENDED_FETCHING = 'HTTP_HERBAL_RECOMMENDED_FETCHING'  
export const HTTP_HERBAL_RECOMMENDED_SUCCESS = 'HTTP_HERBAL_RECOMMENDED_SUCCESS'  
export const HTTP_HERBAL_RECOMMENDED_FAILED = 'HTTP_HERBAL_RECOMMENDED_FAILED'

// Herbal price
export const HTTP_HERBAL_PRICE_FETCHING = 'HTTP_HERBAL_PRICE_FETCHING'  
export const HTTP_HERBAL_PRICE_SUCCESS = 'HTTP_HERBAL_PRICE_SUCCESS'  
export const HTTP_HERBAL_PRICE_FAILED = 'HTTP_HERBAL_PRICE_FAILED'

// Herbal historical price by year
export const HTTP_HERBAL_PRICEYEAR_FETCHING = 'HTTP_HERBAL_PRICEYEAR_FETCHING'  
export const HTTP_HERBAL_PRICEYEAR_SUCCESS = 'HTTP_HERBAL_PRICEYEAR_SUCCESS'  
export const HTTP_HERBAL_PRICEYEAR_FAILED = 'HTTP_HERBAL_PRICEYEAR_FAILED'

// Geo Soil Page
export const HTTP_GEOSOIL_FETCHING = 'HTTP_GEOSOIL_FETCHING'
export const HTTP_GEOSOIL_SUCCESS = 'HTTP_GEOSOIL_SUCCESS'
export const HTTP_GEOSOIL_FAILED = 'HTTP_GEOSOIL_FAILED'
export const HTTP_GEOSOIL_SELECTED_FETCHING = 'HTTP_GEOSOIL_SELECTED_FETCHING'  
export const HTTP_GEOSOIL_SELECTED_SUCCESS = 'HTTP_GEOSOIL_SELECTED_SUCCESS'  
export const HTTP_GEOSOIL_SELECTED_FAILED = 'HTTP_GEOSOIL_SELECTED_FAILED'  

// Geo Salt Page
export const HTTP_GEOSALT_FETCHING = 'HTTP_GEOSALT_FETCHING'
export const HTTP_GEOSALT_SUCCESS = 'HTTP_GEOSALT_SUCCESS'
export const HTTP_GEOSALT_FAILED = 'HTTP_GEOSALT_FAILED'
export const HTTP_GEOSALT_SELECTED_FETCHING = 'HTTP_GEOSALT_SELECTED_FETCHING'  
export const HTTP_GEOSALT_SELECTED_SUCCESS = 'HTTP_GEOSALT_SELECTED_SUCCESS'  
export const HTTP_GEOSALT_SELECTED_FAILED = 'HTTP_GEOSALT_SELECTED_FAILED'  

// CONSTANTS
export const INIT = 'INIT';
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const SET_MAP_CONFIG = 'SET_MAP_CONFIG';
export const QUERY_SUCCESS = 'QUERY_SUCCESS';

// Error Code
export const E_PICKER_CANCELLED = 'E_PICKER_CANCELLED'
export const E_PICKER_CANNOT_RUN_CAMERA_ON_SIMULATOR =
  'E_PICKER_CANNOT_RUN_CAMERA_ON_SIMULATOR'
export const E_PERMISSION_MISSING = 'E_PERMISSION_MISSING'
export const E_PICKER_NO_CAMERA_PERMISSION = 'E_PICKER_NO_CAMERA_PERMISSION'
export const E_USER_CANCELLED = 'E_USER_CANCELLED'
export const E_UNKNOWN = 'E_UNKNOWN'
export const E_DEVELOPER_ERROR = 'E_DEVELOPER_ERROR'
export const TIMEOUT_NETWORK = 'ECONNABORTED' // request service timeout
export const NOT_CONNECT_NETWORK = 'NOT_CONNECT_NETWORK'

//////////////// Localization Begin ////////////////
export const NETWORK_CONNECTION_MESSAGE =
  'Cannot connect to server, Please try again.'
export const NETWORK_TIMEOUT_MESSAGE =
  'A network timeout has occurred, Please try again.'
export const UPLOAD_PHOTO_FAIL_MESSAGE =
  'An error has occurred. The photo was unable to upload.'

// export const apiUrl = 'https://coral-app-hwkgh.ondigitalocean.app/api/v2'
const serviceUrl = process.env.REACT_APP_SERVICE_URL
export const apiUrl = `${serviceUrl}/api/v2`

// export const imageUrl = 'http://61.19.101.249:3000'
export const imageUrl = `${serviceUrl}:3000`

export const YES = 'YES'
export const NO = 'NO'
export const OK = 'ok'
export const NOK = 'nok'
export const LOGIN_STATUS = 'LOGIN_STATUS'
export const USER_ROLES = 'USER_ROLES'
export const TOKEN = 'HerbHukToken'

export const server = {
  LETIN_URL: `user/letin`,
  LOGIN_URL: `user/login`,
  // LOGIN_URL:`/auth`,
  // REGISTER_URL: `user/register`,
  USER_URL: `user`,
  ROLE_URL: `role`,
  VERIFY_URL: `user/verify`,
  AUTH_URL: `authen`,
  SYSTEM_URL: `system`,
  LOGIN_PASSED: `yes`,
  LAND_URL: `geoland`,
  SOIL_URL: `geosoil`,
  SALT_URL: `geosalt`,
  MARKETPLACE_URL: `marketplace`,
  HERBALMARKETPLACE_URL: `herbalmarketplace`,
  FARMERGROUP_URL: `farmergroup`,
  HERBAL_URL: `herbal`,
  GEOSOIL_URL: `geosoil`,
  GEOSALT_URL: `geosalt`,
  PROPERTY_URL: `property`,
  PRICE_URL: `price`,
  FARMER_URL: `farmer`,
  OUTSOURCE_URL: `outsource`,
  RESEARCHINNOVATION_URL: `researchinnovation`,
  KNOWLEDGEBASE_URL: `knowledgebase`,
  PHILOSOPHER_URL: `philosopher`,
  STUDENT_URL: `student`,
  COLLABORATIVEFARM_URL: `collaborativefarm`,
  ENTREPRENEURHERBAL_URL: `entrepreneurherbal`,
  LOG_URL: `log`,
  MANUFACTURER_URL: `manufacturer`,
  ENTREPRENEURMEDICAL_URL: `entrepreneurmedical`,
  REGISTER_URL: `register`,
  // FARMER_ADD_URL: `farmer/add`,
  DASHBOARD_URL: `dashboard`,
  ENTRETYPE_URL: `entretype`,
  PRODUCTTYPE_URL: `producttype`,
  SERVICETYPE_URL: `servicetype`,
  OWNERTYPE_URL: `ownertype`,
  PRODUCETYPE_URL: `producetype`,
  STANDARDTYPE_URL: `standardtype`,
}

// To Make it more secure in JWT, so i'm used id (number) instead
export const ROLES =   {
  'User' : 2001,
  'Editor': 1976,
  'Admin': 5150
}

export const appRoutes = {
  USERS: '/users',
  USERS_LIST: '/users/list',
  USERS_ADD: '/users/add',
  UNKNOWN: '*'
}